services:
  server:
    build:
      context: ./server
    volumes:
      - ./server:/app
    ports:
      - 3000:3000
  client:
    build:
      context: ./client
    volumes:
      - ./client:/app
      - node_modules:/app/node_modules
    ports:
      - 5173:5173

volumes:
  node_modules:
